import { boolean, doublePrecision, integer, pgTable, pgView, text } from 'drizzle-orm/pg-core';

export const calendar = pgTable('calendar', {
	dateStr: text('date_str').primaryKey(),
	dayAfterHoliday: boolean('day_after_holiday'),
	isHoliday: boolean('is_holiday'),
	holidayStreakLen: integer('holiday_streak_len'),
	daysSinceStreakEnd: integer('days_since_streak_end'),
	postStreakSurge: doublePrecision('post_streak_surge'),
	monthSin: doublePrecision('month_sin'),
	monthCos: doublePrecision('month_cos')
});

export const hospitalModelX = pgView('hospital_model_x', {
	hospitalId: text('hospital_id'),
	dateStr: text('date_str'),
	Female: integer('Female'),
	Male: integer('Male'),
	age0To10: integer('age_0_10'),
	age10To20: integer('age_10_20'),
	age20To30: integer('age_20_30'),
	age30To40: integer('age_30_40'),
	age40To50: integer('age_40_50'),
	age50To60: integer('age_50_60'),
	age60To70: integer('age_60_70'),
	age70To80: integer('age_70_80'),
	age80Plus: integer('age_80_plus'),
	A: integer('A'),
	B: integer('B'),
	C: integer('C'),
	D: integer('D'),
	E: integer('E'),
	F: integer('F'),
	G: integer('G'),
	H: integer('H'),
	I: integer('I'),
	J: integer('J'),
	K: integer('K'),
	L: integer('L'),
	M: integer('M'),
	N: integer('N'),
	O: integer('O'),
	P: integer('P'),
	Q: integer('Q'),
	R: integer('R'),
	S: integer('S'),
	T: integer('T'),
	U: integer('U'),
	V: integer('V'),
	W: integer('W'),
	X: integer('X'),
	Y: integer('Y'),
	Z: integer('Z'),
	Other: integer('Other'),
	dayAfterHoliday: boolean('day_after_holiday'),
	isHoliday: boolean('is_holiday'),
	holidayStreakLen: integer('holiday_streak_len'),
	daysSinceStreakEnd: integer('days_since_streak_end'),
	postStreakSurge: doublePrecision('post_streak_surge'),
	monthSin: doublePrecision('month_sin'),
	monthCos: doublePrecision('month_cos')
}).existing();
